server:
  port: 1337


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpabook?serverTimezone=Asia/Seoul
    username: jpa
    password: jpa


jpa:
  hibernate:
    ddl-auto: drop  # ??? ?? ??
  show-sql: true      # SQL ?? ??
  properties:
    hibernate:
      format_sql: true  # SQL pretty print
